const assert=require('node:assert/strict');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
const {chromium}=require('playwright');
const {run}=require('./test_compare.cjs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.clock.install();await page.clock.pauseAt(new Date(Date.now()+1000));
  await page.goto(pathToFileURL(process.argv[2]).href);
  await page.context().setOffline(true);
  await page.locator('#compareMode').click();
  await page.locator('#compareShortest').setInputFiles({name:'shortest.replay.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(run()))});
  const q=run('qos_priority');
  q.modes.qos_priority[83].routing.flows[0].path=[12,23,24,25,14];
  await page.locator('#compareQos').setInputFiles({name:'qos.replay.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(q))});
  assert.match(await page.locator('#compareStatus').innerText(),/Matched/);
  assert.match(await page.locator('#compareSummary').innerText(),/10.00/);
  assert.equal(await page.locator('#comparePhase').inputValue(),'competition');
  await page.locator('#compareFirstDifference').click();
  assert.equal(await page.locator('#compareTime').inputValue(),'83');
  assert.match(await page.locator('#compareRoutes').innerText(),/12 → 23 → 24 → 25 → 14/);
  assert.ok(await page.locator('#compareMap [data-route="qos"]').count()>0);
  assert.equal(await page.locator('#compareMap [data-route="qos"]').first().getAttribute('stroke-dasharray'),'8 5');
  await page.locator('#compareTime').evaluate(e=>{e.value=80;e.dispatchEvent(new Event('input'));});
  assert.match(await page.locator('#compareRouteStatus').innerText(),/Same route/);
  await page.locator('#compareDifferences').check();
  assert.equal(await page.locator('#compareMap [data-route="shared"]').count(),0);
  await page.locator('#compareSpeed').selectOption('10');
  await page.locator('#comparePlay').click();await page.clock.runFor(100);
  assert.equal(await page.locator('#compareTime').inputValue(),'81');
  await page.locator('#comparePlay').click();
  const before=await page.locator('#compareSummary').innerText();
  await page.locator('#compareNext').click();
  assert.equal(await page.locator('#compareSummary').innerText(),before);
  const bad=run('qos_priority');bad.provenance.shaping_sha256='bad';
  await page.locator('#compareQos').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});
  await page.locator('#compareStatus').filter({hasText:'shaping'}).waitFor();
  assert.match(await page.locator('#compareStatus').innerText(),/shaping/);
  assert.equal(await page.locator('#comparePlay').isDisabled(),true);
  await page.locator('#compareQos').setInputFiles({name:'qos.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(q))});
  await page.locator('#compareStatus').filter({hasText:'Matched recorded inputs'}).waitFor();
  await page.screenshot({path:'/tmp/tinyleo-compare-fixture.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#replayMode').click();
  assert.equal(await page.locator('#comparePanel').isVisible(),false);
  assert.equal(await page.locator('#map').isVisible(),true);
  assert.deepEqual(errors,[]);
  const bundled=await browser.newPage();
  const pair=JSON.stringify({shortest:run(),qos:q}).replaceAll('<','\\u003c');
  const html=fs.readFileSync(process.argv[2],'utf8').replace('<script id="comparisonData" type="application/json">null</script>',`<script id="comparisonData" type="application/json">${pair}</script>`);
  await bundled.context().setOffline(true);
  await bundled.setContent(html);
  assert.equal(await bundled.locator('#comparePanel').isVisible(),true);
  assert.match(await bundled.locator('#compareStatus').textContent(),/Matched recorded inputs/);
  assert.equal(await bundled.locator('#comparePlay').isEnabled(),true);
  console.log('PASS: offline Summary, single-map overlay, phase/seek/speed, mismatch rejection, legacy switch and mobile layout.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
